### ISSUE TITLE
Ward errors should cause the build process to abort

### ISSUE THREAD

**Issue by fingolfin** [gap-system/ward#12]
Sometimes, ward fails to preprocess a fail. In the past that used to be mostly silently. It seems Reimer made a change so that at least a warning is output at the end of the build process.

But I think that's not enough -- I think the build process really should immediatly abort in such cases, and print a big fat error.

Case in point: I made a commit that did not even compile. While that is of course ultimately my fault, fact is that I tested it, and it _did_ compile on my system. Or rather, it seemed as if it compiled, but I did not notice the little warning, and then went on to commit. Apparently, one of my changes caused ward to trip over the file with the compile error, so it was never compiled.

**Comment by rbehrends** [comment]
> Case in point: I made a commit that did not even compile. While that is of course ultimately my fault, fact is that I tested it, and it did compile on my system. Or rather, it seemed as if it compiled, but I did not notice the little warning, and then went on to commit. Apparently, one of my changes caused ward to trip over the file with the compile error, so it was never compiled.

I looked at that commit and it should never have compiled, regardless of what Ward did or did not do. The missing include of `pthread.h` led to the type of `pthread_mutex_t` being undefined; this not only resulted in Ward not being able to compile, but the C compiler also refusing to parse it. And in fact, that was what happened to me (because I ran into it myself): GAP didn't build.

Ward proceeds in two stages: First, it tries to parse and analyze the C source code. Second, if that works, it inserts read and write guards in the output; if Ward cannot parse the file, it will simply copy the original code. The warning is to indicate that there may be missing read and write guards.

In short: Ward should never generate code that compiles if the original code was incorrect. If the code compiled, something else may have been wrong (such as a file not actually having been saved yet, the code that was committed not having actually been tested due to a forgotten git add, or something else).

The reason why this isn't an error is that Ward needs to process system include files; when these system include files use non-standard C constructs on some obscure platform, this might break the build process otherwise.

This situation is not ideal in that this makes the build process fragile on platforms that use these gcc/clang-specific features (often even with `-ansi` or `-std=c99`): there are ways to work around this (which involve being able to ignore system header files), but they need to be implemented first.

**Comment by fingolfin** [comment]
For me, something different happened. My guess is that the old file in gen/ was still around, but I did not check this deeply. But yesterday, I run into similar problems half a dozen times, and eventually I settled on always compiling via `rm -rf gen && ./make.hpc`, as that seemed to be the only way to make sure things were good :-(.

**Comment by fingolfin** [comment]
I.e., to drive that home: I repeatedly was in a state, were `./make.hpc` thought everything was up-to-date and thus compiled nothing; but `rm -rf && ./make.hpc` produced a compile error.

**Comment by rbehrends** [comment]
The problem in this case would lie with the dependency checking of `scons` (entirely possible), though, not Ward. I'll have a look at that (dependencies with generated code can be a bit tricky).

**Comment by rbehrends** [comment]
I've submitted a PR for gap that should fix the dependency issue.

**Comment by fingolfin** [comment]
I have encounted problems again, this time because of a parsing problem (which is probably my fault, but that's besides the point). This time, `addguards2` ended up creating a .c file starting with this line:

```
/* ERROR: Ward failed to parse C source */
```

Unfortunately, `addguards2` still exits with exit code 0, so the build system has to perform extra work to detect this.

I think `addguards2` should exit with a non-zero exit code, and perhaps not even output anything at all, except perhaps an error on stderr...

**Comment by fingolfin** [comment]
I hope that the merge of #20 resolves this, so closing for now.
