### ISSUE TITLE
ld: library not found for -lgcc_s.10.4

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/ward#8]
I can't build Ward on Mac at the moment: 

```
...
CC        luajit.o
HOSTLINK  host/minilua
ld: library not found for -lgcc_s.10.4
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [host/minilua] Error 1
make: *** [src/luajit] Error 2
Command failed: make -j 4 -C build/LuaJIT-2.0.0 PREFIX="/Users/alexk/GITREPS/ward/luajit" install
```

**Comment by rbehrends** [comment]
Did you update Xcode to v7 recently? That broke a few things for me, primarily because linker paths changed and I had to rebuild the Homebrew version of `gcc` in order to work. In any event, even if LuaJIT does not build, it should fall back to using the Lua interpreter now. You'll still get the error message above, but the build _should_ continue, unless the Lua interpreter also doesn't build.

**Comment by olexandr-konovalov** [comment]
No, this was some previous Xcode. I have updated it today, and can build Ward again out of the box.
